extra_fn_clean_exts:
    - type: regex
      pattern: '_\w*_S\d+_L\d{3}_R\d_\d{3}'
    - '.LibraryComplexity'

top_modules:
- 'picard'

picard_config:
    general_stats_target_coverage:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30
        - 40
        - 50
        - 60
        - 70
        - 80
        - 90
        - 100

table_columns_visible:
    Picard:
        PCT_PF_READS_ALIGNED: True
        summed_median: True
        summed_mean: False
        PERCENT_DUPLICATION: True
        MEDIAN_COVERAGE: True
        MEAN_COVERAGE: True
        SD_COVERAGE: True
        PCT_5X: True
        PCT_10X: True
        PCT_15X: False
        PCT_20X: True
        PCT_25X: False
        PCT_30X: True
        PCT_40X: True
        PCT_50X: False
        PCT_60X: False
        PCT_70X: False
        PCT_80X: False
        PCT_90X: False
        PCT_100X: False        
        
